#!/bin/bash
#
# Copyright 2023 Guido Trotter <ultrotter@quaqua.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

host="${1:?Usage: $0 hostname}"

destd="${DESTDIR:-$(pwd)}"

autosetupd=$(dirname $0)

# Create a temporary work directory for the apkovl preparation
tmpisod=$(mktemp -d)

mkdir -p ${tmpisod}/etc/autosetup

# Write preseed file but replace the host variable
host=${host} envsubst < ${autosetupd}/setup-alpine-answers.in > ${tmpisod}/etc/autosetup/setup-alpine-answers

cp -a ${autosetupd}/steps ${tmpisod}/etc/autosetup/

# Collect some info from our alpine answers file
. ${tmpisod}/etc/autosetup/setup-alpine-answers

# Write preseed file but replace the host variable
host=${host} user_ssh_key=${USERSSHKEY} envsubst < ${autosetupd}/user-data.in > ${tmpisod}/user-data
host=${host} envsubst < ${autosetupd}/meta-data.in > ${tmpisod}/meta-data


# Create cidata iso image
genisoimage  -output ${destd}/${host}-cidata.iso -volid cidata -joliet -rock ${tmpisod}
#xorrisofs  -output ${destd}/${host}-cidata.iso -volid cidata -joliet -rock ${tmpisod}

rm -rf ${tmpisod}
