#!/bin/bash
#
# Copyright 2023 Guido Trotter <ultrotter@quaqua.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

host="${1:?Usage: $0 hostname}"

autosetupd=$(dirname $0)

destd="${DESTDIR:-/var/lib/libvirt/images}"
tmpd=$(mktemp -d)

DESTDIR=${destd} ${autosetupd}/setup-create-image ${host}

dd if=/dev/zero of=${destd}/${host}-swap.img bs=1M count=1024
chmod 0600 ${destd}/${host}-swap.img

/sbin/mkswap -L ASWVOL ${destd}/${host}-swap.img

host=${host} imgdir=${destd} envsubst < ${autosetupd}/libvirt-domain.xml.in > ${tmpd}/${host}-conf.xml

# create is not persistent:
# virsh create ${tmpd}/${host}-conf.xml

virsh define ${tmpd}/${host}-conf.xml
virsh start ${host}
