#!/bin/bash
#
# Copyright 2023 Guido Trotter <ultrotter@quaqua.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

host="${1:?Usage: $0 hostname}"

destd="${DESTDIR:-$(pwd)}"

autosetupd=$(dirname $0)
. ${autosetupd}/utils

# load default config, and any override
. ${autosetupd}/config
conf_override=${CONF:-${autosetupd}/config}
. ${conf_override}

# Create a temporary work directory for the apkovl preparation
tmpisod=$(mktemp -d)

mkdir -p ${tmpisod}/etc/autosetup

# Write alpine answers file
storage_mode=${STORAGE_MODE:-truncate}
storage_label=${STORAGE_LABEL:-APKOVL}
make_alpine_answers ${tmpisod}/etc/autosetup ${host} ${storage_mode} ${storage_label}

cp -a ${autosetupd}/steps ${tmpisod}/etc/autosetup/

# Collect some info from our alpine answers file
. ${tmpisod}/etc/autosetup/setup-alpine-answers

# Write user-data file but replace some variables
mount_storage="echo 'no local storage to mount'"
if [ "${storage_mode}" != "none" ]; then
  mount_storage="mkdir -p /media/LABEL=${storage_label} && mount /dev/disk/by-label/${storage_label} /media/LABEL=${storage_label}"
fi

host=${host} user_ssh_key=${USERSSHKEY} mount_storage=${mount_storage} envsubst < ${autosetupd}/user-data.in > ${tmpisod}/user-data
host=${host} envsubst < ${autosetupd}/meta-data.in > ${tmpisod}/meta-data

# Create cidata iso image
genisoimage  -output ${destd}/${host}-cidata.iso -volid cidata -joliet -rock ${tmpisod}
#xorrisofs  -output ${destd}/${host}-cidata.iso -volid cidata -joliet -rock ${tmpisod}

rm -rf ${tmpisod}
