#!/bin/bash
#
# Copyright 2023 Guido Trotter <ultrotter@quaqua.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e

host="${1:?Usage: $0 hostname}"

destd="${DESTDIR:-$(pwd)}"

autosetupd=$(dirname $0)

. ${autosetupd}/utils

# load default config, and any override
. ${autosetupd}/config
conf_override=${CONF:-${autosetupd}/config}
. ${conf_override}

# Create a temporary work directory for the volume content
mode=${MODE:-cidata}
tmpvold=$(mktemp -d)

storage_mode=${STORAGE_MODE:-truncate}
if [ "${mode}" = "apkovl" -a "${storage_mode}" != "none" ]; then
  DESTDIR=${tmpvold} ${autosetupd}/setup-create-apkovl ${host}
  mkdir ${tmpvold}/cache
  touch ${tmpvold}/cache/.boot_repository
fi

storage_size=${STORAGE_SIZE:-1G}
storage_label=${STORAGE_LABEL:-APKOVL}
make_volume ${storage_mode} ${destd}/${host}-storage.img ${storage_size} ext4 ${storage_label} ${tmpvold}

rm -rf ${tmpvold}
