#!/bin/bash
#
# Copyright 2023 Guido Trotter <ultrotter@quaqua.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


make_volume () {
  mode="$1"
  target="$2"
  size="$3"
  fs="$4"
  label="$5"
  content="$6"

  case ${mode} in
    none)
        fs="none"
        ;;
    dd)
        dd if=/dev/zero of=${target} bs=1M count=${size}
        ;;
    qemu-img)
        final_target=${target}
        target=${target}.raw
        truncate -s ${size} ${target}
        ;;
    truncate)
        truncate -s ${size} ${target}
        ;;
    *)
        echo "ERROR: unknown make_volume mode ${mode}"
        return 1
   esac

   case ${fs} in
       none)
           ;;
       swap)
           chmod 0600 ${target}
           /sbin/mkswap -L ${label} ${target}
           ;;
       ext4)
           /sbin/mkfs.ext4 -O ^has_journal -L ${label} -d ${content} ${target}
           ;;
   esac

   if [ "${mode}" = "qemu-img" ]; then
     qemu-img convert -f raw -O qcow2 ${target} ${final_target}
   fi

   return 0
}
