#!/bin/sh

set -e

tmpd=$(mktemp -d)

mkdir ${tmpd}/0
DESTDIR=${tmpd}/0 ./setup-create-image test0

if [ ! -f ${tmpd}/0/test0-apkovl.img ]; then
    echo "cannot find output file ${tmpd}/0/test0-apkovl.img"
    exit 1
fi

LSR=$(e2ls -ln ${tmpd}/0/test0-apkovl.img)

if echo ${LSR} | grep -vq test0.apkovl.tar.gz; then
    echo "cannot find apkovl archive in image"
    exit 1
fi

if echo ${LSR} | grep -vq cache; then
    echo "cannot find cache directory in image"
    exit 1
fi

mkdir ${tmpd}/1
olddir=$(pwd)
cd ${tmpd}/1
${olddir}/setup-create-image test1

if [ ! -f ${tmpd}/1/test1-apkovl.img ]; then
    echo "cannot find output file ${tmpd}/1/test1-apkovl.img"
    exit 1
fi

cd -

rm -rf ${tmpd}

echo SUCCESS
