#!/bin/sh

# after setup-alpine and reboot,

is_postinstall=$(df / | grep -c 'sda')
if [ $is_postinstall -eq 0 ]
then
    # is live system
    echo not post-install. skip.
    exit
fi


mkdir -p /host/
# mount -t 9p -o trans=virtio hostslash /host/

echo 'hostslash /host   9p trans=virtio,version=9p2000.L,rw 0 0' >> /etc/fstab
mount -a


ln -s /host/root/* /root/
ln -sf /root/ws/virtual_machine/qemu/b/alpine/root/.??* /root/
ln -sf /root/ws/virtual_machine/qemu/b/alpine/files/etc/local.d/proxy_vm_host.sh /etc/locale.d/

# still need to do this, sice community is commented out by default
echo "https://dl-cdn.alpinelinux.org/alpine/v3.22/main" > /etc/apk/repositories
echo "https://dl-cdn.alpinelinux.org/alpine/v3.22/community" >> /etc/apk/repositories

# already done in answer file
# mkdir -p ~/.ssh/
# echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHI1tpWdNLeV1gwlZBqsmgSREh/njoPj8wbNF8ATWgcP root@eais-bjts6kvodpl1gdpez9p9-0' >> ~/.ssh/authorized_keys


# use proxy
source /etc/profile.d/proxy.sh

apk add bash procps curl wget vim shadow sudo tmux

chsh -s /bin/bash root

command -v gost || cp /host/usr/local/bin/gost /usr/local/bin/
command -v frpc || cp /host/usr/local/bin/frpc /usr/local/bin/



# docker
apk add docker docker-cli-compose 
service docker start

docker --version

# 等待Docker完全启动
sleep 3

# 测试拉取镜像（通过代理）
docker run --rm alpine echo "Docker functions OK"
