#!/bin/sh

set -e

. /etc/autosetup/setup-alpine-answers

# Reboot only if we have lbu support
if [ "${LBUOPTS}" != "none" ]; then
    reboot
    # restart with iso still mounted is ok, though re-run steps wastes some time

    # poweroff
    # give me chance to change vm options, e.g. remove iso
fi
