#!/bin/sh

set -e

if command -v docker
then
    echo OK. no reboot
else
    TMOUT=5
    echo Will reboot in $TMOUT seconds to complete setup. Press Ctrl-C to abort.
    sleep $TMOUT

    reboot
fi


exit


. /etc/autosetup/setup-alpine-answers

# Reboot only if we have lbu support
if [ "${LBUOPTS}" != "none" ]; then

    TMOUT=5
    echo will reboot in $TMOUT seconds. Press Ctrl-C to abort.
    sleep $TMOUT

    reboot
    # restart with iso still mounted is ok, though re-run steps wastes some time

    # poweroff
    # give me chance to change vm options, e.g. remove iso
fi
